config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { invitations: 'users/invitations' }
  root to: 'dashboards#show'
  resource :company, only: %i{new create edit update}
  resource :dashboard, only: %i{show}
  resources :mentors, only: %i(index show)

  resources :mentees do
    resources :check_points, except: %(show) do
      member do
        post :finish
        get :question
        post :answer
      end
    end
  end
end

app/models/mentee.rb
class Mentee < ActiveRecord::Base
  attr_accessor :skip_prepopulate_check_points
  
  belongs_to :company
  has_many :check_points, ->{ order(start_date: 'asc') }, dependent: :destroy
  has_many :mentorships, dependent: :destroy
  has_many :mentors, through: :mentorships, source: :user

  validates :email, :name, presence: true
  validates :email, uniqueness: { scope: :company_id }
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }

  after_create :prepopulate_check_points, unless: :skip_prepopulate_check_points

  def current_check_point
    check_points.where(status: CheckPoint.statuses[:started]).first
  end

  private

  def prepopulate_check_points
    QuestionTemplate::QUESTIONS.each_with_index do |question_name, index|
      check_point = check_points.build(start_date: Date.today + index * 7)
      check_point.build_question(name: question_name)
    end

    save!
    check_points.first.start!
  end

end

app/controllers/mentees_controller.rb
class MenteesController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_admin!, only: [:new, :create, :edit, :update, :destroy]

  def new
    @mentee = current_company.mentees.new
  end

  def index
    if current_user.is_admin?
      @mentees = current_company.mentees
    else
      @mentees = current_user.mentees
    end
  end

  def create
    @mentee = current_company.mentees.create(mentee_params)

    if @mentee.valid?
      input_mentor_ids = (params[:mentee][:mentor_ids] || []).select(&:present?).map { |id| id.to_i }
      input_mentor_ids.each do |id|
        @mentee.mentorships.where(user_id: id).create
      end
      redirect_to @mentee
    else
      render :new
    end
  end

  def update
    @mentee = current_company.mentees.find(params[:id])

    if @mentee.update_attributes(mentee_params)
      current_mentor_ids = @mentee.mentors.pluck(:id)
      input_mentor_ids = (params[:mentee][:mentor_ids] || []).select(&:present?).map { |id| id.to_i }

      removed_mentor_ids = current_mentor_ids - input_mentor_ids
      new_mentor_ids = input_mentor_ids - current_mentor_ids

      @mentee.mentorships.where(user_id: removed_mentor_ids).delete_all
      new_mentor_ids.each do |id|
        @mentee.mentorships.where(user_id: id).create
      end

      redirect_to @mentee
    else
      render :edit
    end
  end

  def edit
    @mentee = current_company.mentees.find(params[:id])
  end

  def destroy
    @mentee = current_company.mentees.find(params[:id])
    @mentee.destroy
    redirect_to mentees_path
  end

  def show
    mentee = current_company.mentees.find(params[:id])
    @presenter = Mentee::ShowMentee.new(mentee)
  end

  private

  def mentee_params
    params.require(:mentee).permit(:name, :email)
  end
end

app/views/mentees/_form.html.slim
= simple_form_for @mentee do |f|
  = f.input :name
  = f.input :email
  = f.association :mentors, collection: current_company.mentors.pluck(:full_name, :id), input_html: { class: 'chosen-select' }
  = f.submit 'Save', class: 'btn btn-primary'
javascript:
  $(".chosen-select").chosen()

app/views/mentees/edit.html.slim
h2.title Edit mentee
= render 'form'

app/views/mentees/index.html.slim
- if current_user.is_admin?
  p.new-mentee-btn
    = link_to 'Create new mentee', new_mentee_path, class: 'btn btn-primary'

.mentor-list
  table.table.table-striped
    th
      td Name
      td Email
      td
      td
      td

    - @mentees.each do |mentee|
      tr
        td= mentee.id
        td= link_to mentee.name, mentee
        td= mentee.email
        td
          - if mentee.mentor_ids.include?(current_user.id)
            =link_to 'Check points', mentee_check_points_path(mentee), class: 'btn btn-success'
        td
          - if current_user.is_admin?
            = link_to 'Edit', edit_mentee_path(mentee), class: 'btn btn-primary'
        td
          - if current_user.is_admin?
            = link_to 'Destroy', mentee_path(mentee), method: :delete, class: 'btn btn-danger'

app/views/mentees/new.html.slim
h2.title New mentee
= render 'form'

app/views/mentees/show.html.slim
= javascript_include_tag "//www.google.com/jsapi", "chartkick"

.mentee
  h1.id Mentee ##{@presenter.id}
  .name
    span.label.label-default Name:
    span.content  #{@presenter.name}
  .email
    span.label.label-default Email:
    span.content  #{@presenter.email}

  p.mentors
    h3.title Mentor
    .list
      - @presenter.mentors.each do |mentor|
        li= mentor.email

  p.buttons
    = link_to 'Edit', edit_mentee_path(@presenter.mentee), class: 'btn btn-primary'
    = link_to 'View check points', mentee_check_points_path(@presenter.mentee), class: 'btn btn-success'

  p.summary
    p.competence
      - if @presenter.good_competence?
        .label.label-success Competent index #{@presenter.competence_index}
      - elsif @presenter.normal_competence?
        .label.label-primary Competent index #{@presenter.competence_index}
      - else
        .label.label-danger Competent index #{@presenter.competence_index}
    p.expectaction
      - if @presenter.good_competence?
        .label.label-success Average expectation #{@presenter.average_expectation}
      - else
        .label.label-danger Average expectation #{@presenter.average_expectation}

    h3 Break down the result:
    = column_chart(@presenter.current_check_point_data)

    h3 Mentee progress
    = line_chart(@presenter.progress_data)