config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { invitations: 'users/invitations' }
  root to: 'dashboards#show'
  resource :company, only: %i{new create edit update}
  resource :dashboard, only: %i{show}
  resources :mentors, only: %i(index show)

  resources :mentees do
    resources :check_points, except: %(show) do
      member do
        post :finish
        get :question
        post :answer
      end
    end
  end
end

app/models/check_point.rb
class CheckPoint < ActiveRecord::Base
  include AASM

  belongs_to :mentee
  has_one :question, dependent: :destroy
  has_many :answers, through: :question

  accepts_nested_attributes_for :question
  enum status: { unstarted: 0, started: 1, finished: 2 }

  scope :past_and_current, -> { where('start_date <= ?', Date.today) }

  validates :start_date, presence: true

  aasm :status do
    state :unstarted, :initial => true
    state :started
    state :finished

    event :start do
      before do
        touch(:started_at)
      end

      transitions :from => :unstarted, :to => :started
    end

    event :finish do
      transitions :from => :started, :to => :finished
    end
  end

  def should_have_started?
    start_date <= Date.today
  end

  def answer_of_mentor(mentor)
    answers.where(user_id: mentor.id).first
  end
end

app/models/mentee.rb
class Mentee < ActiveRecord::Base
  attr_accessor :skip_prepopulate_check_points
  
  belongs_to :company
  has_many :check_points, ->{ order(start_date: 'asc') }, dependent: :destroy
  has_many :mentorships, dependent: :destroy
  has_many :mentors, through: :mentorships, source: :user

  validates :email, :name, presence: true
  validates :email, uniqueness: { scope: :company_id }
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }

  after_create :prepopulate_check_points, unless: :skip_prepopulate_check_points

  def current_check_point
    check_points.where(status: CheckPoint.statuses[:started]).first
  end

  private

  def prepopulate_check_points
    QuestionTemplate::QUESTIONS.each_with_index do |question_name, index|
      check_point = check_points.build(start_date: Date.today + index * 7)
      check_point.build_question(name: question_name)
    end

    save!
    check_points.first.start!
  end

end

app/controllers/check_points_controller.rb
class CheckPointsController < ApplicationController
  def index
    @check_points = current_mentee.check_points.includes(:question).order(start_date: :asc)
  end

  def destroy
    current_mentee.check_points.find(params[:id]).destroy
    redirect_to mentee_check_points_path(current_mentee), notice: 'Check point deleted'
  end

  def new
    @check_point = current_mentee.check_points.build
  end

  def create
    @check_point = current_mentee.check_points.build(check_point_params)
    if @check_point.save
      redirect_to mentee_check_points_path(current_mentee), notice: 'Check point created'
    else
      render action: 'new'
    end
  end

  def edit
    @check_point = current_mentee.check_points.find(params[:id])
  end

  def update
    @check_point = current_mentee.check_points.find(params[:id])
    if @check_point.update(check_point_params)
      redirect_to mentee_check_points_path(current_mentee), notice: 'Check point updated'
    else
      render action: 'edit'
    end
  end

  def finish
    CheckPointService.new(check_point).finish!
    redirect_to mentee_check_points_path(current_mentee)
  end

  def question
    check_point = current_mentee.check_points.find(params[:id])
    @question = check_point.question
    @answer = Answer.new(
      user_id: current_user.id,
      question_id: @question.id
    )
  end

  def answer
    answer_params = params.require(:answer).permit(:question_id, :answer_value, :note)
    answer_params.merge!(user_id: current_user.id)
    @answer = Answer.create(answer_params)
    if @answer.valid?
      redirect_to dashboard_path
    else
      @question = Question.find(answer_params[:question_id])
      render :question
    end
  end

  private

  def check_point
    @check_point ||= current_mentee.check_points.find(params[:id])
  end

  def current_mentee
    @current_mentee ||= Mentee.find(params[:mentee_id])
  end
  helper_method :current_mentee

  def check_point_params
    params.require(:check_point).permit(
      :start_date,
      :question_attributes =>[
        :name
      ]
    )
  end
end

app/views/check_points/_form.html.slim
= simple_form_for [current_mentee, @check_point] do |f|
  = f.simple_fields_for :question do |question_form|
    = question_form.input :name
  = f.input :start_date
  = f.submit 'Save', class: 'btn btn-primary'

app/views/check_points/edit.html.slim
h2 Edit Check point

= render 'form'

app/views/check_points/index.html.slim
h2 Check points

.check-point-list
  table.table.table-striped
    tr
      th #
      th Question
      th  style="width: 200px" Start Date
      th Status
      th style="width: 100px"
      th style="width: 100px"
      
    - @check_points.each_with_index do |check_point, index|
      tr.check-point
        td= index + 1
        td
          - if check_point.question
            = check_point.question.name
        td= check_point.start_date.to_s(:date)
        td= check_point.status

        -  if check_point.unstarted?
          td= link_to 'Edit', edit_mentee_check_point_path(current_mentee, check_point), class: %w{btn btn-default}
          td= link_to 'Delete', mentee_check_point_path(current_mentee, check_point), method: :delete, data: { confirm: 'Do you want to delete this check point?' }, class: %w{btn btn-danger}
        -  elsif check_point.started?
          td
            - if current_mentee.mentor_ids.include?(current_user.id)
              = link_to 'Response', question_mentee_check_point_path(current_mentee, check_point), class: %w{btn btn-default}
          td= link_to 'Finish', finish_mentee_check_point_path(current_mentee, check_point), method: :post, data: { confirm: 'This check point will be automatically close when the next check point starts. Do you want to manually finish this check point?' }, class: %w{btn btn-danger}
        - else
          td
          td

app/views/check_points/new.html.slim
h2 New Check point

= render 'form'

app/views/check_points/question.html.slim
.question
  p Question

  = @question.name

  = simple_form_for(@answer, url: answer_mentee_check_point_path) do |f|
    = f.input :question_id, as: :hidden
    = f.label 'Rating'
    .button-group.answer-value-list(data-toggle="buttons")
      = f.collection_radio_buttons :answer_value, (1..10).to_a, :to_i, :to_i do |value|
        - value.label(class: 'btn btn-default') do
          - concat value.radio_button
          - concat value.value
    = f.input :note, label: 'Comment', placeholder: 'Feel free to elaborate your answer'
    = f.submit 'Submit your response', class: 'btn btn-primary'