config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { invitations: 'users/invitations' }
  root to: 'dashboards#show'
  resource :company, only: %i{new create edit update}
  resource :dashboard, only: %i{show}
  resources :mentors, only: %i(index show)

  resources :mentees do
    resources :check_points, except: %(show) do
      member do
        post :finish
        get :question
        post :answer
      end
    end
  end
end

app/views/layouts/_top_navigation.html.slim
nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      button.navbar-toggle.collapsed aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" type="button"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      .navbar-brand Onboarding
    #navbar.navbar-collapse.collapse
      ul.nav.navbar-nav
        - if user_signed_in?
          - if current_company
            li= link_to 'Dashboard', dashboard_path

            li= link_to 'Mentees', mentees_path
            - if current_user.is_admin?
              li= link_to 'Mentors', mentors_path
        - else
          li.active= link_to 'Home', root_path

      ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          li.dropdown
            a.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button"
              | #{current_user.full_name}
              span.caret
            ul.dropdown-menu
              li= link_to 'Edit Profile', edit_user_registration_path
              li= link_to 'Company profile', edit_company_path
              li.divider role="separator"
              li= link_to 'Sign out', destroy_user_session_path, method: :delete
        - else
          li= link_to 'Sign up', new_user_registration_path
          li= link_to 'Sign in', new_user_session_path

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8" /
    meta content="IE=edge" http-equiv="X-UA-Compatible" /
    meta content="width=device-width, initial-scale=1" name="viewport" /
    title Onboarding
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  body
    .container
      = render 'layouts/top_navigation'
      main
        - if notice
          .alert.alert-success role="alert" = notice
        - if alert
          .alert.alert-danger role="alert" = alert

        = yield